[package]
name = "rotrs"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17", features = ["full"] }
env_logger = "0.11"
log = "0.4"
thiserror = "1.0"
uuid = "1.8"

tokio = { version = "1.37", features = ["full"] }
